### ISSUE TITLE
Stop codons

### ISSUE THREAD

**Issue by har-wradim** [gpertea/gffread#14]
As far as I can tell, asterisk (*) and not dot (.) is the standard character used to denote stop codons in protein sequences, see e.g. [NCBI](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) and emboss:

    $ transeq -filter <<< TAA
    >_1
    *

It is preferable to at least give the user an option to specify the stop codon char [and maybe another one to omit terminal stops altogether].

**Comment by tseemann** [comment]
Also: https://twitter.com/PhilippBayer/status/992418342098030593

**Comment by gpertea** [comment]
So ugly -- how can one look at the `*` character and not think of some sort of wildcard instead of an "ending". While the period character even suggests the rightful *end* of a sentence (translation), and it's also easier to spot on the screen when visually scanning for in-frame stop codons..
I'm not gonna change the default but I provided the `-S` option which can now be used for the `-y` option to achieve this awkward "standard"..

**Comment by har-wradim** [comment]
@gpertea Thanks! I partially agree, but that's the convention. My personal immediate association of a dot in a protein sequence is that of the regex for "any character" or maybe "skipped character" (which is closer to what it designates), not of a full stop.
