### ISSUE TITLE
Include GClib files in this project?

### ISSUE THREAD

**Issue by tseemann** [gpertea/gffread#23]
Can't package this project in conda or brew due to gclib being unreleased.

See also: https://github.com/gpertea/gclib/issues/1

**Comment by TMiguelT** [comment]
It looks like the releases for `gffread` located at http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread_dl have precompiled binaries with the right version of gclib, so even though it's annoying that we can't easily compile this ourselves, this does solve the packaging issue. The `gffread` bioconda recipe just downloads and installs the archives from there: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gffread/meta.yaml

**Comment by tseemann** [comment]
I'm not a fan of packages that depend on pre-built binaries.

**Comment by gpertea** [comment]
> I'm not a fan of packages that depend on pre-built binaries.

Neither am I - so please let's not do that. 
Would it be possible to modify the bioconda recipe to fetch the official gffread source release instead: 
```
http://ccb.jhu.edu/software/stringtie/dl/gffread-{{ version }}.tar.gz
```
..and use that Makefile (patched if/as needed) to build the program from *that* source instead?

>Looks like there are tagged versions now:

Unfortunately those gclib releases are automatically generated by github and do not deal with the original problem - that gclib should **not** be released/distributed/built separately. I use the tags there just as a (loose) way of keeping track of which gclib tag matches a specific gffread release..

However when the source tarball is prepared by the `prep_source.sh` script it should pull the correct matching version of gclib (and only the files *really* needed from gclib) into a consistent and complete source package, made available at the url above as the *official release* - so please use *that* source package instead of the binary packages, if possible.

**Comment by gpertea** [comment]
>so even though it's annoying that we can't easily compile this ourselves

I welcome specific pointers as to how to make the provided source package more compile-friendly for you -- is there any way for me to help with that *without* being forced to add all that autoconf gunk to my projects?
