### ISSUE TITLE
query about incomplete conversion from GFF3 to GTF

### ISSUE THREAD

**Issue by prasundutta87** [gpertea/gffread#27]
Hi,

I was just wondering if I can be explained what is happening with the tool gffread while converting one gff file to gtf file. I used the following command:

    gffread <GFF3_file> -T -o <GTF_file>

When I checked the unique chromosomes/scaffold names to check if the conversion was correct, both gff file and gtf file had different numbers. On digging, I found that some scaffolds (mentioned below) were present exclusively in gff and were not converted to gtf. Example:

    NW_020228737.1  RefSeq  region  1       24009   .       +       .       ID=id827864;Dbxref=taxon:89462;Name=Unknown;breed=Mediterranean;chromosome=Unknown;dev-stage=adult;gbkey=Src;genome=genomic;mol_type=genomic DNA;sex=female;tissue-ty
    ##sequence-region NW_020228738.1 1 24016
    ##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=89462
    NW_020228738.1  RefSeq  region  1       24016   .       +       .       ID=id827865;Dbxref=taxon:89462;Name=Unknown;breed=Mediterranean;chromosome=Unknown;dev-stage=adult;gbkey=Src;genome=genomic;mol_type=genomic DNA;sex=female;tissue-ty
    ##sequence-region NW_020228739.1 1 23921

They are unplaced scaffolds, but why were they not converted? Can someone let me know if I am missing something?

P.S.: I am using the latest version of gffread available on github

**Comment by gpertea** [comment]
It seems to me this is rather a GTF [understanding] issue, not a gffread problem. GTF is a transcript-oriented format, it only supports a very limited set of features (as opposed to GFF3), namely only transcript-describing features (*exon*, *CDS* and that's pretty much it). The *"region"* feature here is not something that GTF cares about -- and frankly neither does gffread (which by default only cares about transcript features as well), since it's not really a transcript or annotation feature, it's a rather useless acknowledgment of a genomic scaffold's presence -- and there is no GTF version of it.

**Comment by prasundutta87** [comment]
Thanks a lot for the reply. It makes sense now. I have many unplaced scaffolds with this annotation in the gff3 file and those were missing from the gtf.

**Comment by prasundutta87** [comment]
Hi,

Could you let me know about these?

NW_020229148.1  Gnomon  exon    23509   23858   .   -   .   ID=id836183;Parent=id836181;Dbxref=GeneID:112582887;gbkey=V_segment;gene=LOC112582887;model_evidence=Supporting evidence includes similarity to: 83%25 coverage of the annotated genomic feature by RNAseq alignments%2C including 22 samples with support for all annotated introns;standard_name=T cell receptor alpha variable 8-3-like
NW_020229148.1  Gnomon  CDS 23989   24034   .   -   0   ID=cds58507;Parent=id836181;Dbxref=GeneID:112582887;exception=rearrangement required for product;gbkey=CDS;gene=LOC112582887;product=T cell receptor alpha variable 8-3-like
NW_020229148.1  Gnomon  CDS 23509   23858   .   -   2   ID=cds58507;Parent=id836181;Dbxref=GeneID:112582887;exception=rearrangement required for product;gbkey=CDS;gene=LOC112582887;product=T cell receptor alpha variable 8-3-like

These were also not transformed..

**Comment by gpertea** [comment]
Look for the feature with ID=id836181 in your GFF3 file, which would be the "parent" of these CDS and exon segments?  Is that a real transcript? It is likely that this "parent" feature was not recognized as a proper transcript by gffread, so that's why it was ignored. And by the description of the "product" there it looks like these exon/CDS entries are part of a variable region (segment) of a T-cell receptor (TCR) protein from the immunoglobulin superfamily.. So it might not be an actual, complete transcript definition there. For many purposes, like RNA-Seq analysis for example, these highly variable "segments" are rather useless, so it shouldn't be a big "loss" if they were not converted to GTF here, in my opinion..

**Comment by prasundutta87** [comment]
Hi,

Thank you for the reply. The Parent of the feature with ID=id836181 is mentioned below:

NW_020229148.1  Gnomon  V_gene_segment  23509   24161   .       -       .       ID=id836181;Parent=gene33995;Dbxref=GeneID:112582887;gbkey=V_segment;gene=LOC112582887;model_evidence=Supporting evidence includes similarity to: 83%25 coverage of the annotated genomic feature by RNAseq alignments%2C including 22 samples with support for all annotated introns;standard_name=T cell receptor alpha variable 8-3-like

which itself is the child of:

NW_020229148.1  Gnomon  gene    23509   24161   .       -       .       ID=gene33995;Dbxref=GeneID:112582887;Name=LOC112582887;gbkey=Gene;gene=LOC112582887;gene_biotype=V_segmentgene_biotype=V_segment

and the whole chromosome is denoted as a region:

NW_020229148.1  RefSeq  region  1       28276   .       +       .       ID=id836180;Dbxref=taxon:89462;Name=Unknown;breed=Mediterranean;chromosome=Unknown;dev-stage=adult;gbkey=Src;genome=genomic;mol_type=genomic DNA;sex=female;tissue-type=blood

So, I guess because the whole unplaced scaffold has been denoted as a region, whatever exon/CDS that was annotated also was rejected and as you mentioned, the variable segments producing incomplete transcripts are actually useless, due to which the NCBI annotation pipeline could not properly annotate it completely. Correct me if I understood incorrectly. 

Another small question, how should I read '83%25 coverage of the annotated genomic feature by RNAseq alignments' - I mean what does it mean?

**Comment by gpertea** [comment]
> So, I guess because the whole unplaced scaffold has been denoted as a region, whatever exon/CDS that was annotated also was rejected and as you mentioned,

No, I did not say that, the fact that the "grand-parent" of that feature is a "region" feature is not relevant here. gffread only ignores the "region" features themselves, but their "child" features are assessed separately, on their own merit. The problem is that usually the parent of exon/CDS features are expected to be "transcripts" or "mRNA" or other recognizable RNA (i.e. transcript) features. Not sure what a "V_gene_segment" is, but it looks like gffread simply did not recognize that as a transcript, at least when it came to GTF conversion. gffread might be wrong discarding these special "features", but as I mentioned before, especially if you want to get a GTF conversion, only well/clearly defined transcript features are converted. I would say this is a rather special case of annotation (a variable segment of a gene..) which, when lost, should not impact the bulk of a RNA-Seq or other analysis -- unless of course the focus of the analysis is exactly these highly variable genes/transcripts.

As for your other question - you can read about "Gnomon", it's NCBI's automated annotation pipeline and in this case they did find some RNA-Seq alignments supporting that variable segment feature there. It might be a real transcript (or part of one), but that feature name "V_gene_segment" just confused gffread and got discarded. Again, this might not be the right thing to do here. 
As for the meaning of `%25` (if you were asking about that) please check the GFF3 specification, e.g. https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md -- it's just an encoding of the percent sign '%'; I usually don't care about encoding anything else but the semi-colon character (`;`), I think encoding any other punctuation is just silly and annoying -- even though the official specification requires it..
