### ISSUE TITLE
missing gene id after converting gff to gtf 

### ISSUE THREAD

**Issue by ze236789** [gpertea/gffread#45]
Hi, 

I am using the gffread v0.11.6 and the command of
./../tool/gffread/gffread -T sample4_prokka_35.gff -o sample4_prokka_35.gtf
to convert a prokka generate gff file to gtf, but found some transcript does not have gene_id. 
Is there a way to solve this problem as it affect the downstream analysis. It was doing good when I used a NCBI downloaded gff file. 

Attached are my gff and generated gtf files.
[sample4_prokka_35.gtf.txt](https://github.com/gpertea/gffread/files/4084605/sample4_prokka_35.gtf.txt)
[sample4_prokka_35.gff.txt](https://github.com/gpertea/gffread/files/4084607/sample4_prokka_35.gff.txt)

Thanks a lot.

**Comment by gpertea** [comment]
That is a severely malformed GFF you have there, the `Parent` attribute is missing for all sub-features (CDS should normally be parented by a transcript or gene features) and in some cases the attributes column (9th) is enclosed by double quotes (why?!) and even so, some of those CDS features (I suppose each of them is a gene, since this is a prokaryotic organism) simply do not have a gene name or any gene ID among the attributes, e.g.: 
```
ID=LBPNIFED_02030;inference=ab initio prediction:Prodigal:2.6;locus_tag=LBPNIFED_02030;product=hypothetical protein
```
The output you obtained is probably missing some of those malformed entries (with double-quoted attributes) and gffread cannot add a gene_id unless some attributes named "gene" "geneID" or "gene_name" are found in the input GFF record..

**Comment by ze236789** [comment]
Thanks for the reply. I am guessing that I should also ask the software
developer for the annotation if I am doing any mistakes here. Any software
you would recommend for annotating draft bins that can produce nice GFF
files?

Thanks

在 2020年1月20日星期一，Geo Pertea <notifications@github.com> 写道：
