### ISSUE TITLE
conversion of gtf to fasta file?

### ISSUE THREAD

**Issue by mathavanpu** [gpertea/gffread#48]
I am working on long-non coding RNAs of human genome, initially created gtf file only contain lncRNA transcript using gffcompare. Now I want to convert the gtf to fasta using gffread when i tried 
the response is
Error parsing strand (F) from GFF line:
please explain this

**Comment by gpertea** [comment]
> please explain this

Was this actually the line what was following that "Error parsing strand.." line in the error message? Or are you asking me to explain that error message -- which is almost impossible without more information at this point..

It looks like gffread encountered a line in your file which it could not parse properly (not a properly formatted GTF/GFF line), apparently that line has an 'F' there in the strand column (?) instead of '+', '-' or '.' (if we're to believe the error message). Is that the complete error message you get? (because it's supposed to be followed by the line that had that problem). 
Perhaps you can share that GTF file with me somehow, to take a look myself if you cannot figure it out? If it were really produced by gffcompare it should not have such problems, perhaps the file was altered in some way before it was given to gffread? Also, please show me the exact command line you used to run gffread and got that error?

**Comment by mathavanpu** [comment]
Thank you for the response

The command I given
/home/madhavan/Downloads/cufflinks-2.2.1.Linux_x86_64/./gffread -w output_lnc.fa -g /media/madhavan/ngs_mathav/Homo_sapiens.GRCh38.dna.toplevel.fa selected.gtf 

I followed this paper
(Transcript-level expression analysis of RNA-seq experiments with HISAT, StringTie and Ballgownhttps://www.nature.com/articles/nprot.2016.095)
My intention is to extract the lncRNA 
**workflow**
fastq -> alignment (hista2)h38->assembly (stringTie) -> stringTTIemerge -> gffcompare -> gffread -> lncRNA fasta sequence

gffcompare generated the transcript abundance file and then  I extracted the lncRNA transcript based on code  [xiou].
finally, I got a gtf  (selected.gtf) file to contain only the lncRNAs now I  need to convert to fasta files
![1232](https://user-images.githubusercontent.com/22020003/73873099-f7dcb980-4876-11ea-96cb-2d4f23c49837.png)
![seleted gtf](https://user-images.githubusercontent.com/22020003/73873102-f9a67d00-4876-11ea-94b4-3a34fc3f669d.png)

**Comment by gpertea** [comment]
The problem is that what your `selected.gtf` file is **not** a GTF file, but another kind of tab-delimited output file among the many created by gffcompare. What was your gffcompare command line?

The actual GTF output of gffcompare should be a file ending with `.annotated.gtf` (or `.combined.gtf`  depending on the other gffcompare options). From that file you should make sure you select the entire GTF record for each of those selected transcript IDs (i.e. all the exons, not just the `transcript` feature line).

Also, I'd suggest using the latest version of gffread (from http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread_dl ), the one included with Cufflinks is very old and I won't be able to deal with any bug reports from that ancient version.
