### ISSUE TITLE
How to extract fasta seq using gene id and not transcript id from stringtie output (gene count matrix file)

### ISSUE THREAD

**Issue by bioinfo17** [gpertea/gffread#6]
Hi Geo,

I came across gffread utilities and was able to find information about extracting transcript fasta sequences using this utility. Could you please advise how to extract fasta seqs using only the gene ids generated by stringtie output (gene counts matrix file). I think I have got this in the wrong section should have posted under stringtie, apologies.

e.g.:

How can I get the fasta sequence for gene MSTRG.1?

KQ473725.1	StringTie	transcript	150	3437	1000	+	.	gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; 
KQ473725.1	StringTie	exon	150	1299	1000	+	.	gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "1"; 
KQ473725.1	StringTie	exon	1348	2107	1000	+	.	gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "2"; 
KQ473725.1	StringTie	exon	2113	3131	1000	+	.	gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "3"; 
KQ473725.1	StringTie	exon	3239	3437	1000	+	.	gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "4"; 
KQ473725.1	StringTie	transcript	150	2194	1000	+	.	gene_id "MSTRG.1"; transcript_id "Pa3770_000380-RA"; gene_name "Pa3770_000380"; ref_gene_id "Pa3770_000380"; 
KQ473725.1	StringTie	exon	150	1299	1000	+	.	gene_id "MSTRG.1"; transcript_id "Pa3770_000380-RA"; exon_number "1"; gene_name "Pa3770_000380"; ref_gene_id "Pa3770_000380"; 
KQ473725.1	StringTie	exon	1348	2107	1000	+	.	gene_id "MSTRG.1"; transcript_id "Pa3770_000380-RA"; exon_number "2"; gene_name "Pa3770_000380"; ref_gene_id "Pa3770_000380"; 
KQ473725.1	StringTie	exon	2113	2194	1000	+	.	gene_id "MSTRG.1"; transcript_id "Pa3770_000380-RA"; exon_number "3"; gene_name "Pa3770_000380"; ref_gene_id "Pa3770_000380"; 
KQ473725.1	StringTie	transcript	2789	3131	1000	-	.	gene_id "MSTRG.2"; transcript_id "Pa3770_000381-RA"; gene_name "Pa3770_000381"; ref_gene_id "Pa3770_000381"; 

Thanks

**Comment by gpertea** [comment]
A gene has multiple transcripts, so I assume your question is rather: how do I get the fasta sequences for all the transcripts from a specific gene (or belonging to a list of genes).
This is indeed not straight forward.. (i.e. not just a gffread command). Given a list of gene_ids, I would probably use something like `fgrep -w -f gene_ids.lst` to select all the transcript entries  from a target GTF and feed that output into ` | gffread -w selected_transcripts.fasta -g genome.fa -`
Hope this helps.

**Comment by bioinfo17** [comment]
I am actually after the sequence of the gene and not transcripts. Since I am using gene count matrix for DE analysis of genes (and not transcript count matrix), is there any other way to find out just the sequence of the gene (this sounds complicated)? Also does it mean if a gene is expressed, all of the transcripts of the gene is expressed. 

As you have mentioned above, a gene has multiple transcripts, does that mean it makes more sense to conduct a DE analysis based on the transcript count matrix and not using gene count matrix. 

Since I am new to all this, your advice has been very useful and I would like to understand the basics around DE analysis before coming to a conclusion. 

Many Thanks

**Comment by gpertea** [comment]
I'd suggest taking some real course on the topic or at least some introductory classes in this field in order to understand the basics -- and better define your goals in the first place: are you interested in gene DE or transcript DE? Why would you even need the gene sequences of entire gene regions anyway?

Sorry for being so blunt but I think the "issues" section in github is not the proper forum for asking for tutorials on these subjects in order to help you *"understand the basics"* -- please do *that* first, using other resource, and *then* come here in order to post bug reports or more to-the-point questions.  I certainly don't have the time to write and post such introductory tutorials here. There is ample online documentation on this topic and nowadays there are also entire free online courses that could help you better than I could (or I have the time) here.

**Comment by bioinfo17** [comment]
I understand, thanks for your time.
