### ISSUE TITLE
handling for empty transcript_id

### ISSUE THREAD

**Issue by murphyte** [gpertea/gffread#84]
I'm following up on an issue one of our users is reporting with NCBI GTF files that traces back to a nuance in gffread GTF handling.

This page links to the GTF2.0 spec:
http://ccb.jhu.edu/software/stringtie/gff.shtml

There is a slightly updated version of the GTF spec (2.2) that is generally backwards compatible but with some clarifications:
https://mblab.wustl.edu/GTF22.html

In particular, the 2.2 spec includes this:
> transcript_id value;     A globally unique identifier for the predicted transcript. If empty, no transcript is associated with this feature.

The 2.2 spec also expands the set of allowed column 3 feature types from 4 to 9, which may or may not be pertinent for gffread.

I'm told gffread reports “no valid ID was found for GFF record” errors for empty transcript_ids. Empty transcript_ids I think are most likely to be used on features other than the 4 or 9 types known to GTF (at least that's the case for NCBI GTF, where we add them on gene features). The GTF2.2 spec does allow to omit transcript_id entirely on features other than the known 4 or 9 types (if you read the spec VERY carefully), but some code (e.g. BEDOPS) expects it to always be present on all features, leading to use of transcript_id "".

I think it would be appropriate to just automatically ignore features with transcript_id "" rather than throwing an error, at least in the context for Stringtie, since it's basically saying that these aren't transcripts. Or ignoring the attribute on feature types like gene would also work.

Thanks for your consideration!

**Comment by gpertea** [comment]
Thank you for pointing out these issues, I was not aware of updates to the GTF specification (kept expecting for this file format to die out and be replaced by GFF3 but it seems to be here to stay). 

It would make it easier to follow up on this issue if you can point me to an example of GTF data that exposes the problem of transcript_id being omitted/empty (and thus triggering that error in gffread).

**Comment by kennyworkman** [comment]
hello @gpertea 

> It would make it easier to follow up on this issue if you can point me to an example of GTF data that exposes the problem of transcript_id being omitted/empty (and thus triggering that error in gffread).

hg38.p14 ([ftp link](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/)) has such an omission

```
root@f924c08ac79ba47fd908-n0-0:~/work/70/6a978bbb78c41fb95e5df093d4c1ca# head GCF_000001405.40_GRCh38.p14_genomic.gtf
#gtf-version 2.2
#!genome-build GRCh38.p14
#!genome-build-accession NCBI_Assembly:GCF_000001405.40
#!annotation-source NCBI Homo sapiens Annotation Release 110
NC_000001.11	BestRefSeq	gene	11874	14409	.	+	.	gene_id "DDX11L1"; transcript_id ""; db_xref "GeneID:100287102"; db_xref "HGNC:HGNC:37102"; description "DEAD/H-box helicase 11 like 1 (pseudogene)"; gbkey "Gene"; gene "DDX11L1"; gene_biotype "transcribed_pseudogene"; pseudo "true";
NC_000001.11	BestRefSeq	transcript	11874	14409	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gbkey "misc_RNA"; gene "DDX11L1"; product "DEAD/H-box helicase 11 like 1 (pseudogene)"; pseudo "true"; transcript_biotype "transcript";
NC_000001.11	BestRefSeq	exon	11874	12227	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gene "DDX11L1"; product "DEAD/H-box helicase 11 like 1 (pseudogene)"; pseudo "true"; transcript_biotype "transcript"; exon_number "1";
NC_000001.11	BestRefSeq	exon	12613	12721	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gene "DDX11L1"; product "DEAD/H-box helicase 11 like 1 (pseudogene)"; pseudo "true"; transcript_biotype "transcript"; exon_number "2";
NC_000001.11	BestRefSeq	exon	13221	14409	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gene "DDX11L1"; product "DEAD/H-box helicase 11 like 1 (pseudogene)"; pseudo "true"; transcript_biotype "transcript"; exon_number "3";
NC_000001.11	BestRefSeq	gene	14362	29370	.	-	.	gene_id "WASH7P"; transcript_id ""; db_xref "GeneID:653635"; db_xref "HGNC:HGNC:38034"; description "WASP family homolog 7, pseudogene"; gbkey "Gene"; gene "WASH7P"; gene_biotype "transcribed_pseudogene"; gene_synonym "FAM39F"; gene_synonym "WASH5P"; pseudo "true";
```

note the last line

**Comment by kennyworkman** [comment]
gtf2.2 has allowed ENSEMBLE + RefSeq to include gene features along with transcripts...
https://www.biostars.org/p/140034/

**Comment by gpertea** [comment]
Interesting - the actual reference (source?) for this seems to be https://mblab.wustl.edu/GTF22.html
Apparently somebody had the brilliant idea to allos  stuff like this (empty string values!) in GTF:
```
40    Twinscan    inter         5141     8522     .    -    .    gene_id ""; transcript_id "";
140    Twinscan    inter_CNS     8523     9711     .    -    .    gene_id ""; transcript_id "";
140    Twinscan    inter         9712     13182    .    -    .    gene_id ""; transcript_id "";
```

This is the kind of abomination that a zombie format like GTF causes as it tries to "evolve" and become something that was never meant to be. GTF was really meant only for annotating **transcripts**, nothing else.  For any other features -- use GFF3, that's why it's there! 

Let's be fair, the vast majority of bioinformatics pipelines care only about transcript/exon/CDS annotation. I assumed/hoped that's why GTF was allowed to survive alongside GFF3 for so long -- as a convenient shortcut for the annotation users to get **only the transcript annotation** whenever that was all they needed, instead of the GFF3 which can have many other genomic features that might not be needed for those annotation users. 

This is an easy fix for me but I really dislike encouraging the survival of bad ideas (which this GTF2.2 perversion clearly is), let's allow "natural selection" of such ideas take its course instead (hopefully).

Meanwhile those who run into such GTF2.2 issues:
* use the GFF3 version of that same annotation, if available
..or if that's not an option: 
* use a grep filter to weed out the badly formatted lines from that GTF2.2 file, e.g. something like this:
```
grep -P '\btranscript_id\s+"[^"]+"'  ann_gtf22.gtf >  ann_fixed.gtf
```
For the hg38.p14 example above:
```
zcat GCF_000001405.40_GRCh38.p14_genomic.gtf.gz | \
   grep -P '\btranscript_id\s+"[^"]+"' > GRCh38.p14_genomic.gtf
```

**Comment by artemyzhigulev** [comment]
Hello, I faced the same Salmon error ` Error: no valid ID found for GFF record ` connected to the gene entries with empty transcript_id "" fields. Should we have a clear warning like in the case of biotypes or automatic filtration step for that?
